### ISSUE TITLE
Out dated info

### ISSUE THREAD

**Issue by Swan38** [WartaPoirier-corp/cours-ima#8]
Salut, votre site est vrm top, il m'a bcp servi depuis le début de l'année. Je vous fait juste remarquer qu'il n'est pas à jour (les feuilles de TD de MAT302 ont changés) et les liens zoom n'y sont pas. Je ne sais pas si vous avez abandonné le projet mais en tout cas bravo !

**Comment by elegaanz** [comment]
On met plus trop à jour non, on avait pas l'impression que ça servait beaucoup, mais si ça sert on peut rajouter les trucs au fur et à mesure. Et si ça vous amuse de faire des PR pour ajouter des trucs faites vous plaisir aussi.

**Comment by elegaanz** [comment]
C'est à jour normalement, j'ai tout rajouté.

**Comment by elegaanz** [comment]
Pour les liens Zoom on peut pas vraiment les mettre directement parce que c'est pas des vrais liens, c'est géré avec du JS sur Moodle, et de toute façon c'est pas une bonne idée de mettre des liens zoom dans la nature comme ça.
